#!/usr/bin/env node
const chalk = require('chalk')
const args = process.argv

const commands = ['pruneAll', 'prune', 'help']

const usage = function() {
  const usageText = `
  git-bonsai helps you prune branches merged to master.

  usage:
    git-bonsai <command>

    commands can be:
  `

  console.log(usageText)
}
// used to log errors to the console in red color
function errorLog(error) {
  const eLog = chalk.red(error)
  console.log(eLog)
}

// we make sure the length of the arguments is exactly three
if (args.length > 3) {
  errorLog(`only one argument can be accepted`)
  usage()
}

if (commands.indexOf(args[2]) == -1) {
  errorLog('invalid command passed')
  usage()
}

switch(args[2]) {
  case 'pruneAll':
    break
  case 'prune':
  checkBranch()
    break
  case 'help':
    usage()
    break

  default:
    //errorLog('invalid command passed')
}

function checkBranch(){
	console.log('TACO')
}